# Generated by Django 5.2.5 on 2025-08-18 16:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('BEACH', 'Beach'), ('MOUNTAIN', 'Mountain'), ('HISTORICAL', 'Historical'), ('ADVENTURE', 'Adventure'), ('WILDLIFE', 'Wildlife'), ('CULTURAL', 'Cultural'), ('FOOD', 'Food & Wine'), ('RELAX', 'Relaxation')], max_length=20)),
                ('best_season', models.CharField(choices=[('WINTER', 'Winter'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('AUTUMN', 'Autumn'), ('ALL', 'All Year')], max_length=20)),
                ('budget', models.CharField(choices=[('CHEAP', 'Cheap ($)'), ('MODERATE', 'Moderate ($$)'), ('LUXURY', 'Luxury ($$$)')], max_length=20)),
                ('activities', models.TextField(help_text='Comma separated list of activities')),
                ('image', models.ImageField(blank=True, null=True, upload_to='destination_images/')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weather', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='destinations.destination')),
            ],
        ),
    ]
