# Generated by Django 5.2.5 on 2025-08-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherinfo',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
