# Generated by Django 5.2.5 on 2025-08-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_weatherinfo_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image',
        ),
        migrations.AddField(
            model_name='destination',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
