# Generated by Django 5.2.5 on 2025-08-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_remove_destination_image_destination_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherinfo',
            name='icon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
