# Generated by Django 5.2.5 on 2025-08-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_weatherinfo_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image_url',
        ),
    ]
