# Generated by Django 5.2.5 on 2025-08-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_remove_destination_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
