# Generated by Django 5.2.5 on 2025-08-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_destination_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='budget',
            field=models.CharField(choices=[('CHEAP', 'Budget ($)'), ('MODERATE', 'Moderate ($$)'), ('LUXURY', 'Luxury ($$$)')], max_length=20),
        ),
        migrations.DeleteModel(
            name='WeatherInfo',
        ),
    ]
